version: "3.9"

services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:

